### ISSUE TITLE
PyPi project

### ISSUE THREAD

**Issue by idanpa** [ZhiqingXiao/calcpy#1]
Hello @ZhiqingXiao, 
I'm writing here too in case you don't see my email from a month ago (and a few emails from a year ago):

I see that right after I submitted this issue pypi/support#3648 you created this repo with some boilerplate and uploaded it to PyPi.

Could you please update if you plan to use https://pypi.org/project/calcpy ?

Had you informed me about this a year ago, I would not have attempted to use the same name. Your response is highly appreciated!

**Comment by ZhiqingXiao** [comment]
Hi @idanpa, thank you for your attention to the project calcpy. The project calcpy has been planed and under development for many years since around 2021, and we have released and open-sourced some of its functionalities.
I just noticed that you are working on a project with the same name. I am sorry that I did not notice your project as well as your emails earlier. Congratulations to your project on having so many wonderful functionalities in such as short time. In the meanwhile, could you please consider using an alternative project name (such as termcalc, calcip, ipexec, etc), if you want to publish it in PyPi? Thanks.
